config/routes.rb
Rails.application.routes.draw do
 
  # get 'authors/index'
  # get 'authors/show'
  # get 'authors/new'
  # get 'authors/edit'
  # get 'authors/delete'
  # get 'books/index'
  # get 'books/show'
  # get 'books/new'
  # get 'books/edit'
  # get 'books/delete'
  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'
  # get 'categories/delete'

  
  namespace :api,defaults:{format: :json} do
    namespace :v1 do
      resources :books
  resources :authors
  resources :categories
  
  
end
end

# root to:"home#index"
# get "home/books"


# get "home/authors"
# get "home/categories"


 



 resources :categories do

  member do
    get :delete

 end
end

 resources :books do

  member do
    get :delete

 end
end


 resources :authors do

  member do
    get :delete

 end
end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/author.rb
class Author < ApplicationRecord

    has_many :book_through_authors
    has_many :books, through: :book_through_authors
   
end

app/controllers/api/v1/authors_controller.rb
module Api 
    module V1

  class AuthorsController < ApplicationController
    # before_action :authorize_access_reqques!
    skip_before_action :verify_authenticity_token

    before_action :set_artist, only: %i[ show update destroy ]

    # GET /artists
    def index
      @authors = Author.all
        
      render json: @authors
    end

    # GET /artists/1
    def show
      render json: @authors
    end

    # POST /artists
    def create
      @authors = Author.new(author_params)

      if @authors.save
        render json: @authors, status: :created, location: @authors
      else
        render json: @authors.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /artists/1
    def update
      if @authors.update(author_params)
        render json: @authors
      else
        render json: @authors.errors, status: :unprocessable_entity
      end
    end

    # DELETE /artists/1
    def destroy
      @authors.destroy
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_artist
        @authors = Author.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def author_params
        
    
    
        params.require(:author).permit(:name)


      end
  end
end
end  


app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @author=Author.all
  end

  def show
    @author =Author.find(params[:id])

  end

  def new
    @author = Author.new

  end


  def create
    @author = Author.new(authors_params)
    if @author.save
      redirect_to(authors_path)
    elsif
    render("error1") 
    end

  end

  def edit
    @author =Author.find(params[:id])
 

  end

  def update
    @author =Author.find(params[:id])
     
    if @author.update(authors_params)
      redirect_to(authors_path)
    elsif
    render("error1") 
    end
  end

  def delete
    @author =Author.find(params[:id])

  end

  def destroy
    @author =Author.find(params[:id])

    if @author.destroy
      # @book.destroy
      redirect_to(authors_path)
    elsif
    render("error1") 
    end
  end

  def Error1 
    render("error1",)
  end

  private
  def authors_params
    params.require(:author).permit(:name)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<table summary="author for field">
<tr>
<th><strong>Name : <strong></th>
<td><%=f.text_field(:name)%></td>
</tr>



</table>

app/views/authors/delete.html.erb
<div class="delete index">
<%=link_to("Back To Book ",authors_path,:class =>"action new")%>
<h1>Delete</h1>
<%=form_for(@author,:method => "delete") do |f|%>
<table class="delete author " >

<p>Are you sure you want to delete this author name?</p>
<p class="reference-name"><%=@author.name%>




</table>

<div class="forms-button">
<%=f.submit("Delete Content")%>
</div>

<%end%>


</div>

app/views/authors/edit.html.erb
<div class="Author new">
<%=link_to("Back To author",authors_path,:class=>"back-link")%>
<h1>Edit Author Name</h1>
<%=form_for(@author,:method=>"patch") do |f|%>
<%=render(:partial=>'form',:locals=>{:f=>f} )%>
<div class="forms-button">
<%=f.submit("Update Author")%>
</div>
<%end%>
</div>

app/views/authors/error1.html.erb
<h1>Not Be Created</h1>

app/views/authors/index.html.erb
<div class="Authors index">
<h1>Add new Author</h1>
<%=link_to("Adding new author ","authors/new",:class =>"action new")%>
<table class="Authors"  summary="Authors list">

<tr class="header">
<th>#</th>
<th>Name</th>
</tr>

<%@author.each do |b| %>
<tr>
<td><%=b.id%></td>
<td><%=link_to(b.name,:controller => :books, :id => b.id)%></td>

<td class="action">
<%=link_to("Show",author_path(b.id), :class=>"action show")%>

<%=link_to("Edit",edit_author_path(b.id), :class=>"action edit")%>
<%=link_to("Delete",delete_author_path(b.id), :class=>"action delete")%>
</td>
</tr>
<%end%>
</table>
</div>

app/views/authors/new.html.erb
<div class="author new">
<%=link_to("Back To Author",authors_path,:class=>"back-link")%>
<h1>Created Author</h1>
<%=form_for(@author,:method=>"post") do |f|%>
<%=render(:partial=>'form',:locals=>{:f=>f} )%>

<div class="forms-button">
<%=f.submit("Create Auhtor")%>
</div>
<%end%>
</div>

app/views/authors/show.html.erb
<div class="Show index">


<%=link_to("Back To Book ",authors_path,:class =>"action new")%>

<h1>Show Auhtor</h1>
<table class="lisitng" summary="Show books">

<tr class="header">
<tr>
<th>Author ID</th>
<td><%=@author.id%>
</tr></tr>

<tr>
<th>Name</th>
<td><%=@author.name%>
</tr></tr>


<tr>
<th>Created</th>
<td><%=@author.created_at%>
</tr></tr>

<tr>
<th>Updated</th>
<td><%=@author.updated_at%>
</tr></tr>


</table>
</div>