config/routes.rb
Rails.application.routes.draw do
 
  # get 'authors/index'
  # get 'authors/show'
  # get 'authors/new'
  # get 'authors/edit'
  # get 'authors/delete'
  # get 'books/index'
  # get 'books/show'
  # get 'books/new'
  # get 'books/edit'
  # get 'books/delete'
  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'
  # get 'categories/delete'

  
  namespace :api,defaults:{format: :json} do
    namespace :v1 do
      resources :books
  resources :authors
  resources :categories
  
  
end
end

# root to:"home#index"
# get "home/books"


# get "home/authors"
# get "home/categories"


 



 resources :categories do

  member do
    get :delete

 end
end

 resources :books do

  member do
    get :delete

 end
end


 resources :authors do

  member do
    get :delete

 end
end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :book_through_categories
    has_many :categories, through: :book_through_categories

    has_many :book_through_authors
    has_many :authors, through: :book_through_authors

end

app/controllers/api/v1/books_controller.rb
module Api 
    module V1

  class BooksController < ApplicationController
    # before_action :authorize_access_reqques!
    skip_before_action :verify_authenticity_token
    before_action :set_artist, only: %i[ show update destroy ]

    # GET /artists
    def index
      @books = Book.all

      render json: @books
    end

    # GET /artists/1
    def show
      render json: @books
    end

    # POST /artists
    def create
      @books = Book.new(book_params)

      if @books.save
        
        render json: @books , status: :created, location: @books
      else
        render json: @books.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /artists/1
    def update
      if @books.update(book_params)
        render json: @books
      else
        render json: @books.errors, status: :unprocessable_entity
      end
    end

    # DELETE /artists/1
    def destroy
      @books.destroy
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_artist
        @books = Book.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def book_params
        
    params.require(:book).permit(:name,:pages)

      end
  end
end
end  


app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :set_book ,only: [:show,:edit, :update,:delete, :destroy]


  def index
    # @author = Author.find(params[:author])
    @book=Book.all
  end

  def show
    @book =Book.find(params[:id])

  end

  def new
   
   @author = Author.find(params[:id])


    @book = @author.books.build
  end


  def create
    @author = Author.find(params[:id])
    @book = @author.books.build(params[:book])
    if @book.save
      redirect_to new_book_path(:id => @author.id)
    elsif
    render("error1") 
    end

  end

  def edit
    # @book =Book.find(params[:id])
 

  end

  def update
    # @book =Book.find(params[:id])
     
    if @book.update(books_params)
      redirect_to(books_path)
    elsif
    render("error1") 
    end
  end

  def delete
    # @book =Book.find(params[:id])

  end

  def destroy
    # @book =Book.find(params[:id])

    if @book.destroy
      # @book.destroy
      redirect_to(books_path)
    elsif
    render("error1") 
    end
  end

  def Error1 
    render("error1",)
  end

  private

  def set_book
    # @author = Author.find(params[:author])

    @book =Book.find(params[:id])

  end
  
  def books_params
    params.require(:book).permit(:name)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb

<table summary="books for field">
<tr>
<th><strong>Name : <strong></th>
<td><%=f.text_field(:name)%></td>
</tr>



</table>

app/views/books/delete.html.erb
<div class="delete index">
<%=link_to("Back To Book ",books_path,:class =>"action new")%>
<h1>Delete</h1>
<%=form_for(@book,:method => "delete") do |f|%>
<table class="delete book " >

<p>Are you sure you want to delete this subject?</p>
<p class="reference-name"><%=@book.name%>




</table>

<div class="forms-button">
<%=f.submit("Delete Content")%>
</div>

<%end%>


</div>

app/views/books/edit.html.erb
<div class="Book new">
<%=link_to("Back To Book",books_path,:class=>"back-link")%>
<h1>Edit Book</h1>
<%=form_for(@book,:method=>"patch") do |f|%>
<%=render(:partial=>'form',:locals=>{:f=>f} )%>
<div class="forms-button">
<%=f.submit("Update Book")%>
</div>
<%end%>
</div>

app/views/books/error1.html.erb
<h1>Not Be Created </h1>

app/views/books/index.html.erb
<div class="Books index">
<h1>Add new book</h1>
<%=link_to("Adding new book ","books/new",:class =>"action new")%>
<table class="Books"  summary="Books list">

<tr class="header">
<th>#</th>
<th>Name</th>
</tr>

<%@book.each do |b| %>
<tr>
<td><%=b.id%></td>
<td><%=b.name%></td>

<td class="action">
<%=link_to("Show",book_path(b.id), :class=>"action show")%>
 <%=link_to("Edit",edit_book_path(b.id), :class=>"action edit")%>
  <%=link_to("Delete",delete_book_path(b.id), :class=>"action delete")%>
</td>
</tr>
<%end%>
</table>
</div>

app/views/books/new.html.erb
<div class="Book new">
<%=link_to("Back To Book",books_path,:class=>"back-link")%>
<h1>Created Book</h1>
<%=form_for(@book,:method=>"post") do |f|%>
<%=render(:partial=>'form',:locals=>{:f=>f} )%>


<div class="forms-button">
<%=f.submit("Create Book")%>
</div>
<%end%>
</div>

app/views/books/show.html.erb
<div class="Show index">


<%=link_to("Back To Book ",books_path,:class =>"action new")%>

<h1>Show Books</h1>
<table class="lisitng" summary="Show books">

<tr class="header">
<tr>
<th>Book ID</th>
<td><%=@book.id%>
</tr></tr>

<tr>
<th>Name</th>
<td><%=@book.name%>
</tr></tr>


<tr>
<th>Created</th>
<td><%=@book.created_at%>
</tr></tr>

<tr>
<th>Updated</th>
<td><%=@book.updated_at%>
</tr></tr>


</table>
</div>