config/routes.rb
Rails.application.routes.draw do
 
  # get 'authors/index'
  # get 'authors/show'
  # get 'authors/new'
  # get 'authors/edit'
  # get 'authors/delete'
  # get 'books/index'
  # get 'books/show'
  # get 'books/new'
  # get 'books/edit'
  # get 'books/delete'
  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'
  # get 'categories/delete'

  
  namespace :api,defaults:{format: :json} do
    namespace :v1 do
      resources :books
  resources :authors
  resources :categories
  
  
end
end

# root to:"home#index"
# get "home/books"


# get "home/authors"
# get "home/categories"


 



 resources :categories do

  member do
    get :delete

 end
end

 resources :books do

  member do
    get :delete

 end
end


 resources :authors do

  member do
    get :delete

 end
end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :book_through_categories
    has_many :books, through: :book_through_categories

end

app/controllers/api/v1/categories_controller.rb
module Api 
    module V1

  class  CategoriesController < ApplicationController
    # before_action :authorize_access_reqques!
    skip_before_action :verify_authenticity_token

    before_action :set_artist, only: %i[ show update destroy ]

    # GET /artists
    def index
      @categories = Category.all

      render json: @categories
    end

    # GET /artists/1
    def show
      render json: @categories
    end

    # POST /artists
    def create
      @categories = Category.new(categories_params)

      if @categories.save
        render json: @categories, status: :created, location: @categories
      else
        render json: @categories.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /artists/1
    def update
      if @categories.update(categories_params)
        render json: @categories
      else
        render json: @categories.errors, status: :unprocessable_entity
      end
    end

    # DELETE /artists/1
    def destroy
      @categories.destroy
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_artist
        @categories = Category.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def categories_params
        
    params.require(:category).permit(:name)

      end
  end
end
end  


app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category=Category.all
  end

  def show
    @category =Category.find(params[:id])

  end

  def new
    @category = Category.new

  end


  def create
    @category = Category.new(categories_params)
    if @category.save
      redirect_to(categories_path)
    elsif
    render("error1") 
    end

  end

  def edit
    @category =Category.find(params[:id])
 

  end

  def update
    @category =Category.find(params[:id])
     
    if @category.update(categories_params)
      redirect_to(categories_path)
    elsif
    render("error1") 
    end
  end

  def delete
    @category =Category.find(params[:id])

  end

  def destroy
    @category =Category.find(params[:id])

    if @category.destroy
      # @book.destroy
      redirect_to(categories_path)
    elsif
    render("error1") 
    end
  end

  def Error1 
    render("error1",)
  end

  private
  def categories_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<table summary="category for field">
<tr>
<th><strong>Name : <strong></th>
<td><%=f.text_field(:name)%></td>
</tr>



</table>

app/views/categories/delete.html.erb
<div class="delete index">
<%=link_to("Back To Category ",categories_path,:class =>"action new")%>
<h1>Delete</h1>
<%=form_for(@category,:method => "delete") do |f|%>
<table class="delete category " >

<p>Are you sure you want to delete this subject?</p>
<p class="reference-name"><%=@category.name%>




</table>

<div class="forms-button">
<%=f.submit("Delete Content")%>
</div>

<%end%>


</div>

app/views/categories/edit.html.erb
<div class="Category new">
<%=link_to("Back To Category",categories_path,:class=>"back-link")%>
<h1>Edit Category</h1>
<%=form_for(@category,:method=>"patch") do |f|%>
<%=render(:partial=>'form',:locals=>{:f=>f} )%>


<div class="forms-button">
<%=f.submit("Update Category")%>
</div>
<%end%>
</div>

app/views/categories/error1.htm.erb
<h1>Not Be Created</h1>

app/views/categories/index.html.erb
<div class="Category index">
<h1>Add new book</h1>
<%=link_to("Adding new category ","categories/new",:class =>"action new")%>
<table class="Category"  summary="Category list">

<tr class="header">
<th>#</th>
<th>Name</th>
</tr>

<%@category.each do |b| %>
<tr>
<td><%=b.id%></td>
<td><%=b.name%></td>

<td class="action">
<%=link_to("Show",category_path(b.id), :class=>"action show")%>
 <%=link_to("Edit",edit_category_path(b.id), :class=>"action edit")%>
  <%=link_to("Delete",delete_category_path(b.id), :class=>"action delete")%>
</td>
</tr>
<%end%>
</table>
</div>

app/views/categories/new.html.erb
<div class="Category new">
<%=link_to("Back To Category",categories_path,:class=>"back-link")%>
<h1>Created Category</h1>
<%=form_for(@category,:method=>"post") do |f|%>
<%=render(:partial=>'form',:locals=>{:f=>f} )%>

<div class="forms-button">
<%=f.submit("Create Category")%>
</div>
<%end%>
</div>

app/views/categories/show.html.erb
<div class="Show index">


<%=link_to("Back To Category ",categories_path,:class =>"action new")%>

<h1>Show Categories</h1>
<table class="lisitng" summary="Show Category">

<tr class="header">
<tr>
<th>Category ID</th>
<td><%=@category.id%>
</tr></tr>

<tr>
<th>Name</th>
<td><%=@category.name%>
</tr></tr>


<tr>
<th>Created</th>
<td><%=@category.created_at%>
</tr></tr>

<tr>
<th>Updated</th>
<td><%=@category.updated_at%>
</tr></tr>


</table>
</div>